version: "3"

networks:
  web:
    driver: bridge

services:
  blog:
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: admin654321
      WORDPRESS_DB_NAME: wordpress
    labels:
      - 'traefik.backend=blog'
      - 'traefik.frontend.rule=Host: stationpro.ml, www.stationpro.ml'
      - 'traefik.port=80'
    networks:
      - web
    depends_on:
      - mysql
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: admin654321
      MYSQL_DATABASE: wordpress
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - web
    labels:
      - traefik.enable=false
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    labels:
      - traefik.backend=phpmyadmin
      - traefik.frontend.rule=Host:admin.stationpro.ml
    networks:
      - web
    depends_on:
      - mysql
  redis:
    image: redis
    labels:
     - traefik.enable=false
