version: "3.7"

services:
  blog:
    image: nginx
    restart: always
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./config:/etc/nginx/conf.d/default.conf
    labels:
      - 'traefik.frontend.rule=Host:wordpress.stationpro.ml'
      - "traefik.docker.network=traefik_default"
      - 'traefik.port=80'
    depends_on:
      - php
    networks:
      - web
  php:
    image: php:7.2-cli
    restart: always

volumes:
    db-data:
    web-data:
networks:
  web:
    external:
      name: traefik_default

